### ISSUE TITLE
Closing the program after a while (~20 minutes) takes a long time

### ISSUE THREAD

**Issue by codyhan94** [Whisperrr/SensitivityRandomizer#1]
I pressed ctrl-c in the terminal to close the program after it had been running for around 20 minutes, and it hung (disabling mouse input in the meantime) for a good 30 seconds before closing. Can this be reduced?

**Comment by Whisperrr** [comment]
Fixed in v0.5 :) This was an issue with QuickEdit mode being enabled in the Command Prompt properties. Anyone who experienced freezing like this should be good to go now.
