### ISSUE TITLE
Time step

### ISSUE THREAD

**Issue by thecccut** [Whisperrr/SensitivityRandomizer#3]
My timestep is stuck on 0.001

**Comment by Whisperrr** [comment]
To be able to access the Timestep variable, you have to set "Type=0" in the settings.ini file.

Copied from the readme:
If you set Type = 1 (generating a smooth curve), you won't be able to modify the timestep variable. It will be forced at a very small value (0.001) to ensure the generated sensitivity curve is actually smooth. To be able to modify this variable, you'll need to first have Type = 0 set above to specify you no longer want a smooth sensitivity curve.
